/**
 * Created by luowen on 2018/2/6
 */

exports.STOCK_EX = {
  A: 'A',
  US: 'US',
  HK: 'HK',
  INT: 'INT',
};

exports.CHAT_ROOM_STOCK = ['us stock', '加密币学习群', '呼啦呼啦，喔哈喔哈'];
exports.EXCLUDE_COINS = "BTC,ETH,XRP,BCH,ADA,LTC,NEO,XLM,EOS,XEM,MIOTA,DASH,XMR,TRX,USDT,LSK,VEN,ETC,ICX,QTUM,BTG,XRB,PPT,OMG,ZEC,STEEM,BNB,SNT,BCN,XVG,SC,STRAT,BTS,VERI,MKR,WTC,AE,REP,KCS,ZRX,WAVES,DOGE,RHOC,DCR,HSR,DGD,KNC,ARDR,KMD,GAS,ETN,ARK,ZIL,DRGN,LRC,BAT,DCN,ELF,DGB,PLR,R,PIVX,GBYTE,ZCL,ETHOS,FUN,NAS,QASH,BTM,CNX,DENT,CND,GNT,SYS,BTX,IOST,GXS,SALT,POWR,AION,KIN,SMART,MONA,FCT,AGI,XPA,XZC,BNT,REQ,PART,QSP,RDD,NXS,MAID,NXT,ENG,PAY,WAX,ICN,IGNIS,GNO,NEBL,GAME,LINK,RDN,SUB,HPB,VTC,EMC,BLOCK,POE,ANT,PPP,MED,DEW,XP,SKY,CVC,UNITY,BTCD,ENJ,STORJ,DTR,XDN,ZEN,ITC,SRN,UBQ,HTML,TNB,BCO,VEE,RLC,ACT,BLZ,VIBE,AST,MANA,MDS,AGRS,STORM,RCN,MCO,NAV,LEND,SPHTX,SAN,PPC,XBY,DBC,SNGLS,UTK,PAC,OST,TEL,MTL,BIX,XAS,AMB,CMT,THETA,TNC,RPX,COB,XCP,WABI,PAYX,SNM,CTR,EDG,NULS,ADX,QRL,EMC2,BAY,VIA,NLG,WGR,ECA,ATM,INS,APPC,MLN,DATA,EDO,TRAC,FUEL,SPANK,MOD,IDH,ETP,INT,TNT,WINGS,MGO,GVT,UKG,ION,BRD,NGC,LBC,DNT,OCN,BURST,TRIG,CDT,ONION,LKK,HST,BDG,CLOAK,CAPP,SOC,MNX,QLC,CRW,GRID,DAT,GTO,MER,LUN,SXDT,SLS,ECC,DPY,DCT,VIB,HVN,ADT,TAAS,AEON,TKN,SAFEX,PRE,1ST,THC,GRS,PURA,JINN,COSS,PRL,XSPEC,INK,BCC,KEY,NMC,QBT,IOC,MOON,TSL,CFI,PEPECASH,KRM,BITCNY,CV,SWFTC,TIO,YOYOW,MTH,COLX,BLT,DMD,POT,SHIFT,VOX,TRST,EVX,HMQ,NET,FTC,ART,LA,XSH,IXT,CAN,TIX,SIB,FLASH,DLT,PASC,DIME,ZSC,MOT,SBD,LEO,NLC2,FAIR,WRC,SNC,VRC,AMP,PPY,UNO,XWC,CAT,PHR,MDA,BCAP,PRO,DNA".split(/,/g);

exports.SYMBOL_TYPE = {
  "11": "A 股", "12": "B 股", "13": "权证", "14": "期货", "15": "债券",
  "21": "开基", "22": "ETF", "23": "LOF", "24": "货基", "25": "QDII", "26": "封基",
  "31": "港股", "32": "窝轮", "33": "港指数",
  "41": "美股", "42": "外期",
  '81': '债券', '82': '债券',
  "111": "A股"
};
